# https://ci.appveyor.com/project/orbingol/nurbs-python

# Partly inspired from
#   http://tjelvarolsson.com/blog/how-to-continuously-test-your-python-code-on-windows-using-appveyor/
#   https://github.com/ogrisel/python-appveyor-demo
#   https://www.appveyor.com/docs/appveyor-yml/

version: 1.0.{build}

## Build tags only
#skip_non_tags: true

# Fetch repository as a zip archive
shallow_clone: true

# branches to build
branches:
  # whitelist
  only:
    - master
    - 3.x
    - devmaster

  # blacklist
  except:
    - gh-pages
    - 2.x
    - 2.x-json

environment:
  global:
    MPLBACKEND: "Agg"

  matrix:
    - PYTHON: "C:\\Python27-x64"
      PYTHON_VERSION: "2.7.15"
      PYTHON_ARCH: "64"

    - PYTHON: "C:\\Python34-x64"
      PYTHON_VERSION: "3.4.4"
      PYTHON_ARCH: "64"

    - PYTHON: "C:\\Python35-x64"
      PYTHON_VERSION: "3.5.3"
      PYTHON_ARCH: "64"

    - PYTHON: "C:\\Python36-x64"
      PYTHON_VERSION: "3.6.6"
      PYTHON_ARCH: "64"

# PR settings
pull_requests:
  do_not_increment_build_number: true

install:
  # If there is a newer build queued for the same PR, cancel this one.
  # The AppVeyor 'rollout builds' option is supposed to serve the same
  # purpose but it is problematic because it tends to cancel builds pushed
  # directly to master instead of just PR builds (or the converse).
  # credits: JuliaLang developers.
  - ps: if ($env:APPVEYOR_PULL_REQUEST_NUMBER -and $env:APPVEYOR_BUILD_NUMBER -ne ((Invoke-RestMethod `
        https://ci.appveyor.com/api/projects/$env:APPVEYOR_ACCOUNT_NAME/$env:APPVEYOR_PROJECT_SLUG/history?recordsNumber=50).builds | `
        Where-Object pullRequestId -eq $env:APPVEYOR_PULL_REQUEST_NUMBER)[0].buildNumber) { `
          throw "There are newer queued builds for this pull request, failing early." }

  # Install Python (from the official .msi of http://python.org) and pip when
  # not already installed.
  - ps: if (-not(Test-Path($env:PYTHON))) { & appveyor\install.ps1 }

  # Prepend newly installed Python to the PATH of this build (this cannot be
  # done from inside the PowerShell script as it would require to restart
  # the parent CMD process).
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"

  # Upgrade to the latest version of pip to avoid it displaying warnings
  # about it being out of date.
  - "python -m pip install --disable-pip-version-check --upgrade pip"

  # Upgrade setuptools
  - "python -m pip install --upgrade setuptools"

  # Install numpy & matplotlib
  - "python -m pip install numpy matplotlib"

  # Install pytest
  - "python -m pip install pytest"

#  # Install wheel
#  - "python -m pip install wheel"

# Install the python module
build_script:
  - cmd: '%CMD_IN_ENV% python setup.py develop'

# Run the project tests
test_script:
  - cmd: '%CMD_IN_ENV% python setup.py test'

#after_test:
#  # If tests are successful, create binary packages for the project.
#  - "%CMD_IN_ENV% python setup.py bdist_wheel"
#  - "%CMD_IN_ENV% python setup.py bdist_wininst -p win32"
#  - "%CMD_IN_ENV% python setup.py bdist_wininst -p win-amd64"
#  - "%CMD_IN_ENV% python setup.py bdist_msi -p win32"
#  - "%CMD_IN_ENV% python setup.py bdist_msi -p win-amd64"
#
#artifacts:
#  # Archive the generated packages in the ci.appveyor.com build report.
#  - path: dist\*

#on_success:
  # Upload the content of dist/*.whl to a public wheelhouse
  # - "do uploading operations here"

deploy: off
