# https://travis-ci.org/orbingol/NURBS-Python

dist: xenial
sudo: false

language: python

# branches to build
branches:
  only:
    - master  # latest version
    - devmaster  # latest development version
    - 4.x  # v4.x series
    - 3.x  # v3.x series
    - 2.x  # v2.x series
    - travisci-testing  # Travis-CI testing

# build matrix
matrix:
  include:
    - python: 2.7
      env: TOXENV=py27,test,codecov

    - python: 3.4
      env: TOXENV=py34,test

    - python: 3.5
      env: TOXENV=py35,test

    - python: 3.6
      env: TOXENV=py36,test

    - python: 3.7
      env: TOXENV=py37,test,codecov

    - python: pypy3.5
      env: TOXENV=pypy3,test

    - name: "Performance testing on Python 3.5"
      python: 3.5
      env: TOXENV=py35,performance-full
      if: branch = master OR branch = travisci-testing

    - name: "Performance testing on PyPy 3.5"
      python: pypy3.5
      env: TOXENV=pypy3,performance
      if: branch = master OR branch = travisci-testing

# install packages
install:
  - pip install tox

# run tox
script:
  - tox
