# https://travis-ci.org/orbingol/NURBS-Python

language: python

python:
  - "2.7"
  - "3.6"
  - "pypy"

# branch safelist
branches:
  only:
    - master
    - 3.x
    - 2.x

# install required packages
install:
  - pip install setuptools --upgrade
  - pip install pytest pytest-cov
  - pip install codecov

# install package and run tests
#script: "python setup.py develop && pytest --cov=./"
script: 'python setup.py develop && python setup.py test -a "--cov=./"'

# call at the end of CI build
after_success:
  - codecov
